//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid ID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.Guid CreateUser { get; set; }
        public string Hospital { get; set; }
        public string VisitTarget { get; set; }
        public string CallNotes { get; set; }
        public Nullable<int> VisitFee { get; set; }
        public Nullable<int> TransportFee { get; set; }
        public string Misc { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
